### ISSUE TITLE
ExamenOnline/V2.0/Alta modelo de examen. #60

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Examen-Online#16]
Al dar de alta un examen deben aparecer todas las subclases, como aparecen al dar de alta un usuario en Front.

![](https://user-images.githubusercontent.com/27014552/29080747-fec5b31e-7c36-11e7-8677-3a7f4d4e7307.jpg)

![](https://user-images.githubusercontent.com/27014552/29080773-13837f48-7c37-11e7-8f30-ab83ca190849.png)

**Comment by alewalsh** [comment]
Por ahora, esto queda como se habia pedido anteriormente.
